import { m as generatedMessages } from "$lib/paraglide/messages.js";
import enMessages from "../../messages/en.json";
import * as archetypeIntroModule from "$lib/paraglide/messages/sim_matchmaking_archetype_intro.js";
import * as archetypeUserMatchesTitleModule from "$lib/paraglide/messages/sim_matchmaking_archetype_usermatches_title1.js";

export * from "$lib/paraglide/messages.js";

/** Generated by Paraglide (`bun run i18n:compile`). File name suffix may change if the message is duplicated in-catalog. */
const archetypeIntroKey = "sim.matchmaking.archetype.intro";
const archetypeUserMatchesTitleKey = "sim.matchmaking.archetype.userMatches.title";

type Locale = "en" | "de" | "it" | "es" | "pt-br";
type LocalizedString = string;
export type SimulatorMessageTranslator = (
  inputs?: Record<string, unknown>,
  options?: { locale?: Locale },
) => LocalizedString;

function renderWithValues(messageTemplate: unknown, values: Record<string, unknown> = {}): string {
  if (typeof messageTemplate !== "string") {
    return String(messageTemplate);
  }

  return messageTemplate.replace(/\{([^{}]+)\}/g, (_, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : `{${key}}`,
  );
}

export const m = new Proxy(
  generatedMessages as unknown as Record<string, SimulatorMessageTranslator>,
  {
    get(target, propertyKey) {
      if (typeof propertyKey !== "string") {
        return Reflect.get(target, propertyKey);
      }

      const message = Reflect.get(target, propertyKey);
      if (typeof message === "function") {
        return message;
      }

      return (
        inputs: Record<string, unknown> = {},
        _options?: { locale?: Locale },
      ): LocalizedString => {
        const fallbackMessage = (enMessages as Record<string, unknown>)[propertyKey];
        if (typeof fallbackMessage === "string") {
          return renderWithValues(fallbackMessage, inputs);
        }

        return `[${propertyKey}]`;
      };
    },
  },
) as Record<string, SimulatorMessageTranslator>;

const archetypeIntroFn = (archetypeIntroModule as unknown as Record<string, unknown>)[
  archetypeIntroKey
];

const archetypeUserMatchesTitleFn = (
  archetypeUserMatchesTitleModule as unknown as Record<string, unknown>
)[archetypeUserMatchesTitleKey];

/** Archetype lobby hero copy — direct Paraglide binding so Vite cannot drop this message via `m[...]` + Proxy. */
export const simMatchmakingArchetypeIntro: SimulatorMessageTranslator =
  typeof archetypeIntroFn === "function"
    ? (archetypeIntroFn as SimulatorMessageTranslator)
    : (inputs = {}) => {
        const template =
          (enMessages as Record<string, unknown>)[archetypeIntroKey] ??
          "Create a match by specifying which archetype you want to find. The purpose of this feature is to help you test a specific matchup as thoroughly as possible.";
        return renderWithValues(template, inputs) as LocalizedString;
      };

/** Archetype match list card title — direct Paraglide binding so Vite cannot drop this message via `m[...]` + Proxy. */
export const simMatchmakingArchetypeUserMatchesTitle: SimulatorMessageTranslator =
  typeof archetypeUserMatchesTitleFn === "function"
    ? (archetypeUserMatchesTitleFn as SimulatorMessageTranslator)
    : (inputs = {}) => {
        const template =
          (enMessages as Record<string, unknown>)[archetypeUserMatchesTitleKey] ??
          "Matches Created by Players";
        return renderWithValues(template, inputs) as LocalizedString;
      };
